# Generated by Django 5.0.6 on 2024-06-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_station', to='api.station'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='more_information',
            field=models.CharField(default='Extra', max_length=100),
        ),
    ]
