# Generated by Django 5.0.4 on 2024-04-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fuel_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='number_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='api.vehichle'),
        ),
    ]
