# Generated by Django 5.0.6 on 2024-06-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_fuel_fuel_station_remove_fuel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='user',
        ),
    ]
