# Generated by Django 5.0.4 on 2024-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_fuel_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
        ),
    ]
