# Generated by Django 5.0.4 on 2024-04-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fuel_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='number_plate',
            new_name='fuel_plate',
        ),
    ]
