# Generated by Django 5.0.4 on 2024-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vehichle_vehichle_type_alter_fuel_fuel_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='mileage',
            field=models.FloatField(default=0),
        ),
    ]
