# Generated by Django 5.0.4 on 2024-06-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_canaccessdriverdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanAccessDriverDashboard',
        ),
    ]
