# Generated by Django 5.0.6 on 2024-06-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_admin_delete_engineer_remove_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
