# Generated by Django 5.0.6 on 2024-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_is_admin_remove_user_is_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_engineer',
            field=models.BooleanField(default=False),
        ),
    ]
