# Generated by Django 5.0.6 on 2024-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
