# Generated by Django 5.0.6 on 2024-06-14 12:20

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='status',
            field=models.CharField(default='Rejected', max_length=20),
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_hired', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('vehichle_attached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineers', to='api.vehichle')),
            ],
            bases=(models.Model, api.models.ExtraMixin),
        ),
    ]
