# Generated by Django 5.0.6 on 2024-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_fuel_status_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
