# Generated by Django 5.0.6 on 2024-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_fuel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
