# Generated by Django 5.0.6 on 2024-06-21 08:45

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_fuel_fuel_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=20)),
                ('date_of_jobcard', models.DateField()),
                ('parts_needed', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('jobcard_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='api.vehichle')),
            ],
            bases=(models.Model, api.models.ExtraMixin),
        ),
    ]
