# Generated by Django 5.0.6 on 2024-06-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_jobcard_repair_alter_jobcard_jobcard_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='userfuel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
