# Generated by Django 5.0.6 on 2024-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_fuel_user_alter_fuel_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='project',
            field=models.CharField(default='CSQUARED', max_length=25),
        ),
    ]
