# Generated by Django 5.0.6 on 2024-06-24 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_fuel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfuel', to=settings.AUTH_USER_MODEL),
        ),
    ]
