# Generated by Django 5.0.6 on 2024-06-25 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_maintenance_assigned_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='assigned_engineer',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='assignedEngineer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
