# Generated by Django 5.0.6 on 2024-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_maintenance_assigned_engineer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_chief_executive_officer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_chief_transport_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_human_resource_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_procurement_manager',
            field=models.BooleanField(default=False),
        ),
    ]
