# Generated by Django 5.0.6 on 2024-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_is_admin_user_is_chief_executive_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='cto_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='fully_procured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='hr_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='partially_procured',
            field=models.BooleanField(default=False),
        ),
    ]
